src/djangular/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from rest_framework_jwt.views import obtain_jwt_token

from ang.views import AngularTemplateView

from accounts.views import (login_view, register_view, logout_view)
from posts import views as posts_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', posts_views.post_list),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
    url(r'^', include("posts.urls", namespace="posts")),
    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/posts/', include("posts.api.urls", namespace="posts-api")),
    url(r'^api/users/', include("accounts.api.urls", namespace="users-api")),
    url(r'^api/comments/', include("comments.api.urls", namespace="comments-api")),
    url(r'^api/templates/(?P<item>[A-Za-z0-9\_\-\.\/]+)\.html$', AngularTemplateView.as_view()),
    url(r'^comments/', include("comments.urls", namespace="comments")),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'', TemplateView.as_view(template_name="ang/home.html")),
]

src/posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.post_list, name="list"),
	url(r'^create/$', views.post_create),
	url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name="detail"),
	url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name="update"),
	url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete, name="delete"),
]

src/posts/models.py
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.safestring import mark_safe

from markdown_deux import markdown
from comments.models import Comment

from .utils import get_read_time

class PostManager(models.Manager):
	def active(self):
		return super().filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
	return "{}/{}".format(instance.id, filename)

class Post(models.Model):
	user 		= models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	title 		= models.CharField(max_length=120)
	slug 		= models.SlugField(unique=True, blank=True)
	image 		= models.ImageField(upload_to=upload_location, null=True, blank=True, width_field="width_field", height_field="height_field")
	height_field= models.IntegerField(default=0)
	width_field	= models.IntegerField(default=0)
	content 	= models.TextField()
	draft 		= models.BooleanField(default=False)
	publish 	= models.DateField(auto_now=False, auto_now_add=False, blank=True) 
	timestamp 	= models.DateTimeField(auto_now_add=True)
	updated 	= models.DateTimeField(auto_now=True)
	read_time 	= models.TimeField(null=True, blank=True)

	objects = PostManager()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"slug": self.slug})

	def get_api_url(self):
		return reverse("posts-api:detail", kwargs={"slug": self.slug})

	class Meta:
		ordering = ["-timestamp"]

	def get_markdown(self):
		content = self.content
		return mark_safe(markdown(content))

	@property
	def comments(self):
		instance = self
		qs = Comment.objects.filter_by_instance(instance)
		return qs

	@property
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type


def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "{}-{}".format(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)

	if instance.content:
		html_string = instance.get_markdown()
		read_time_var = get_read_time(html_string)
		instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post

class PostForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(widget=forms.SelectDateWidget)
	class Meta:
		model = Post

		fields = [
			"title",
			"content",
			"image",
			"draft",
			"publish",
		]

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django Angular{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block head_extra %}
    {% endblock %}
</head>

<body>
    <div id="fb-root"></div>
    <script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=198459453897675";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>
    {% include 'message_display.html' %}

    <div class="container">
        <div class="breadcrumb">
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'posts:list' %}">Posts</a></li>
            {% block post_detail_link %}
            {% endblock %}
            {% if not request.user.is_authenticated %}
            <li class="pull-right"><a href="{% url 'login' %}">Login</a></li>
            <li class="pull-right"><a href="{% url 'register' %}">Register</a></li>
            {% else %}
            <li class="pull-right"><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
            
        </div>
        {% block content %} {% endblock %}
    </div>
    <script   src="https://code.jquery.com/jquery-3.2.0.min.js"   integrity="sha256-JAW99MJVpJBGcbzEuXk4Az05s/XyDdBomFqNlM3ic+I="   crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>

    <script>
        $(document).ready(function(){
            $(".content-markdown").each(function(){
                var content = $(this).text();
                var markedContent = marked(content);
                $(this).html(markedContent);
            })

            $(".post-detail-item img").each(function(){
                $(this).addClass("img-responsive");
            })

            var titleItem = $("#id_title");
            $("#preview-title").text(titleItem.val());
            
            var contentInput = $("#id_content");

            function setContent(value){
                var markedContent = marked(value);
                $("#preview-content").html(markedContent);
                $("#preview-content img").each(function(){
                    $(this).addClass("img-reponsive");
                })
            }

            setContent(contentInput.val());

            contentInput.keyup(function(){
                var newContent = $(this).val();
                setContent(newContent);
            })

            $(".comment-reply-btn").click(function(e){
                e.preventDefault();
                $(this).parent().next(".comment-reply").fadeToggle();
            })
            

            
        })
    </script>
</body>

</html>

src/templates/form.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block head_extra %}
{% endblock %}

{% block content %}
<div class="col-sm-6">
    <h1>{{ title }}</h1>
    <form action="" method="POST">
        {% csrf_token %} <div>
        	{{ form|crispy }}
        </div>
        <input type="submit" value="Login">
    </form>
</div>
{% endblock %}

src/templates/message_display.html
<div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
</div>